### ISSUE TITLE
can't run standalone

### ISSUE THREAD

**Issue by hutchic** [debops/ansible-lvm#14]
I can't get ansible to get past the when statement [here](https://github.com/debops/ansible-lvm/blob/master/tasks/main.yml#L42-L45). If I nuke that when everything works fine.

I tried to debug which part of the when is failing but got a little lost in the logic as it were. Any pointers or assistance debugging would be greatly appreciated

**Comment by drybjed** [comment]
DebOps roles require the environment that is prepared by the [debops.core](https://github.com/debops/ansible-core/) role - it's the only one that's required explicitly by all the others. Can you try running it on a host before the `debops.lvm` role and see if that helps?

**Comment by hutchic** [comment]
Yup that solves it. Could that be added to the README?

**Comment by drybjed** [comment]
@hutchic Maybe... But I would rather make the role work even if the role is not present. I'll look into it when I will have a bit of time.
