### ISSUE TITLE
Manage filesystems - syntax error

### ISSUE THREAD

**Issue by soalhn** [debops/ansible-lvm#8]
When I run the role, it fails on the task "Manage filesystems" with the following syntax error (manage_lvm.yml - line no 55):
`fatal: [example.com]: FAILED! => {"failed": true, "msg": "The conditional check 'lvm__logical_volumes|d(False) and item.vg|d() and item.lv|d() and item.size|d() and item.state|d('present') != 'absent' and ((item.mount|d() and item.fs|d()) or item.fs|d()))' failed. The error was: template error while templating string: unexpected ')'. String: {% if lvm__logical_volumes|d(False) and item.vg|d() and item.lv|d() and item.size|d() and item.state|d('present') != 'absent' and ((item.mount|d() and item.fs|d()) or item.fs|d())) %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/root/.local/share/debops/debops-playbooks/roles/debops.lvm/tasks/manage_lvm.yml': line 55, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Manage filesystems\n  ^ here\n"}`

The bug is in the line no 65 - too many closing brackets, it should be like this:
`((item.mount|d() and item.fs|d()) or item.fs|d())`

**Comment by drybjed** [comment]
Thanks, I'll check that out ASAP.
